import ball from "../Assets/Svgs/ball.svg";
import black_ball from "../Assets/Svgs/ball_black.svg";
import stripped_ball from "../Assets/Svgs/ball_stripped.svg";
import black_bat from "../Assets/Svgs/bat_black.svg";
import brown_bat from "../Assets/Svgs/bat_brown.svg";
import rounded_bat from "../Assets/Svgs/bat_rounded.svg";
import thick_bat from "../Assets/Svgs/bat_thick.svg";
import white_helmet from "../Assets/Svgs/helmet_white.svg";
import helmet from "../Assets/Svgs/helmet.svg";
import pitch from "../Assets/Svgs/pitch.svg";
import player from "../Assets/Svgs/player.svg";
import star from "../Assets/Svgs/star.svg";
import lined_star from "../Assets/Svgs/star_lined.svg";

export const Ball = ball;
export const Black_ball = black_ball;
export const Stripped_ball = stripped_ball;
export const Black_bat = black_bat;
export const Brown_bat = brown_bat;
export const Rounded_bat = rounded_bat;
export const Thick_bat = thick_bat;
export const White_helmet = white_helmet;
export const Helmet = helmet;
export const Pitch = pitch;
export const Player = player;
export const Star = star;
export const Lined_star = lined_star;
