export const Female_Players = [
  {
    name: "Mirriam Edung",
    position: "Pitcher",
    Jersey: "8",
    gender: "Female",
    image: require("../Assets/Batting.jpg"),
  },
  {
    name: "Mirriam Edung",
    position: "Pitcher",
    Jersey: "8",
    gender: "Female",
    image: require("../Assets/Batting.jpg"),
  },
  {
    name: "Mirriam Edung",
    position: "Pitcher",
    Jersey: "8",
    gender: "Female",
    image: require("../Assets/Batting.jpg"),
  },
  {
    name: "Mirriam Edung",
    position: "Pitcher",
    Jersey: "8",
    gender: "Female",
    image: require("../Assets/Batting.jpg"),
  },
  {
    name: "Mirriam Edung",
    position: "Pitcher",
    Jersey: "8",
    gender: "Female",
    image: require("../Assets/Batting.jpg"),
  },
  {
    name: "Mirriam Edung",
    position: "Pitcher",
    Jersey: "8",
    gender: "Female",
    image: require("../Assets/Batting.jpg"),
  },
  {
    name: "Mirriam Edung",
    position: "Pitcher",
    Jersey: "8",
    gender: "Female",
    image: require("../Assets/Batting.jpg"),
  },
  {
    name: "Mirriam Edung",
    position: "Pitcher",
    Jersey: "8",
    gender: "Female",
    image: require("../Assets/Batting.jpg"),
  },
  {
    name: "Mirriam Edung",
    position: "Pitcher",
    Jersey: "8",
    gender: "Female",
    image: require("../Assets/Batting.jpg"),
  },
];
export const Male_Players = [
  {
    name: "Luis Kimutai",
    position: "Pitcher",
    Jersey: "8",
    gender: "male",
    image: require("../Assets/Batting.jpg"),
  },
  {
    name: "Antonicm",
    position: "Catcher",
    Jersey: "8",
    gender: "male",
    image: require("../Assets/Batting.jpg"),
  },
  {
    name: "Eleli Ayub",
    position: "First Baseman",
    Jersey: "8",
    gender: "male",
    image: require("../Assets/Batting.jpg"),
  },
  {
    name: "Job",
    position: "First Baseman",
    Jersey: "8",
    gender: "male",
    image: require("../Assets/Batting.jpg"),
  },
  {
    name: "Simon",
    position: "Third Baseman",
    Jersey: "8",
    gender: "male",
    image: require("../Assets/Batting.jpg"),
  },
  {
    name: "Haaron",
    position: "Outfield",
    Jersey: "8",
    gender: "male",
    image: require("../Assets/Batting.jpg"),
  },
  {
    name: "Amos",
    position: "Outfield",
    Jersey: "8",
    gender: "male",
    image: require("../Assets/Batting.jpg"),
  },
  {
    name: "Jeff",
    position: "Shot Stop",
    Jersey: "8",
    gender: "male",
    image: require("../Assets/Batting.jpg"),
  },
  {
    name: "Charles",
    position: "Outfield",
    Jersey: "8",
    gender: "male",
    image: require("../Assets/Batting.jpg"),
  },
  {
    name: "Ian",
    position: "Outfield",
    Jersey: "8",
    gender: "male",
    image: require("../Assets/Batting.jpg"),
  },
];
