export const Female_Players = [
  {
    name: "Liz",
    position: "Pitcher",
    Jersey: "15",
    gender: "Female",
    image: require("../Assets/Players/Liz.jpg"),
  },
  {
    name: "Pretty Joy",
    position: "Pitcher",
    Jersey: "7",
    gender: "Female",
    image: require("../Assets/Players/Pretty.jpg"),
  },
  {
    name: "Sheila",
    position: "Pitcher",
    Jersey: "4",
    gender: "Female",
    image: require("../Assets/Players/Sheila.jpg"),
  },
  {
    name: "Hallinter",
    position: "Catcher",
    Jersey: "5",
    gender: "Female",
    image: require("../Assets/Players/Hallinter.jpg"),
  },
  {
    name: "Chebi",
    position: "First Base",
    Jersey: "3",
    gender: "Female",
    image: require("../Assets/Players/Chebii.jpg"),
  },
  {
    name: "Natasha",
    position: "Second Base",
    Jersey: "7",
    gender: "Female",
    image: require("../Assets/Players/Natasha.jpg"),
  },
  {
    name: "Imelda",
    position: "Shot Stop",
    Jersey: "9",
    gender: "Female",
    image: require("../Assets/Players/Imelda.jpg"),
  },
  {
    name: "Nakeel",
    position: "Third Base",
    Jersey: "8",
    gender: "Female",
    image: require("../Assets/Players/Nakeel.jpg"),
  },
  {
    name: "Bridgit",
    position: "Third Base",
    Jersey: "10",
    gender: "Female",
    image: require("../Assets/Batting.jpg"),
  },
  {
    name: "Bree",
    position: "Outfielder",
    Jersey: "6",
    gender: "Female",
    image: require("../Assets/Players/Bridgit.jpg"),
  },
  {
    name: "Mirriam",
    position: "Outfielder",
    Jersey: "12",
    gender: "Female",
    image: require("../Assets/Players/Mirriam.jpg"),
  },
  {
    name: "Yvonne",
    position: "Outfielder",
    Jersey: "16",
    gender: "Female",
    image: require("../Assets/Players/Yvonne.jpg"),
  },
];
export const Male_Players = [
  {
    name: "Luis Kimutai",
    position: "Pitcher",
    Jersey: "5",
    gender: "male",
    image: require("../Assets/Batting.jpg"),
  },
  {
    name: "Ravi",
    position: "Pitcher",
    Jersey: "22",
    gender: "male",
    image: require("../Assets/Players/Ravi.jpg"),
  },
  {
    name: "Titus",
    position: "Pitcher",
    Jersey: "13",
    gender: "male",
    image: require("../Assets/Players/Titus.jpg"),
  },
  {
    name: "Tony",
    position: "Catcher",
    Jersey: "12",
    gender: "male",
    image: require("../Assets/Players/Tony.jpg"),
  },
  {
    name: "Antonicm",
    position: "Catcher",
    Jersey: "69",
    gender: "male",
    image: require("../Assets/Players/Anto.jpg"),
  },
  {
    name: "Omar",
    position: "Catcher",
    Jersey: "15",
    gender: "male",
    image: require("../Assets/Players/Omar.jpg"),
  },
  {
    name: "Eleli",
    position: "First Baseman",
    Jersey: "4",
    gender: "male",
    image: require("../Assets/Players/Ayub.jpg"),
  },
  {
    name: "Job",
    position: "Second Baseman",
    Jersey: "21",
    gender: "male",
    image: require("../Assets/Players/Job.jpg"),
  },
  {
    name: "Simon",
    position: "Third Baseman",
    Jersey: "6",
    gender: "male",
    image: require("../Assets/Players/Simo.jpg"),
  },
  {
    name: "Haaron",
    position: "Outfield",
    Jersey: "3",
    gender: "male",
    image: require("../Assets/Players/Aaron.jpg"),
  },
  {
    name: "Amos",
    position: "Outfield",
    Jersey: "8",
    gender: "male",
    image: require("../Assets/Players/Amos.jpg"),
  },
  {
    name: "Jeff",
    position: "Shot Stop",
    Jersey: "9",
    gender: "male",
    image: require("../Assets/Players/Jefff.jpg"),
  },
  {
    name: "Charles",
    position: "Outfield",
    Jersey: "7",
    gender: "male",
    image: require("../Assets/Players/Much.jpg"),
  },
  {
    name: "Ian",
    position: "Outfield",
    Jersey: "10",
    gender: "male",
    image: require("../Assets/Players/Ian.jpg"),
  },
  {
    name: "Mutemba",
    position: "Outfielder",
    Jersey: "11",
    gender: "male",
    image: require("../Assets/Players/Mutemba.jpg"),
  },
  {
    name: "Isaack",
    position: "Outfield",
    Jersey: "17",
    gender: "male",
    image: require("../Assets/Players/Izo.jpg"),
  },
];
