import Njau from "../Assets/Batting.jpg";
import Liz from "../Assets/Players/Liz.jpg";
import Pretty from "../Assets/Players/Pretty.jpg"
import Sheila from "../Assets/Players/Sheila.jpg"
import Hallinter from "../Assets/Players/Hallinter.jpg"
import Chebi from "../Assets/Players/Chebii.jpg"
import Natasha from "../Assets/Players/Natasha.jpg"
import Mwende from "../Assets/Batting.jpg"
import Kimutai from "../Assets/Batting.jpg"
import Ravi from "../Assets/Players/Ravi.jpg"
import Titus from "../Assets/Players/Titus.jpg"
import Tony from "../Assets/Players/Tony.jpg"
import Omar from "../Assets/Players/Omar.jpg"
import Anto from "../Assets/Players/Anto.jpg"
import Yvonne from "../Assets/Players/Yvonne.jpg"
import Mirriam from "../Assets/Players/Mirriam.jpg"
import Bridgit from "../Assets/Players/Bridgit.jpg"
import Nakeel from "../Assets/Players/Nakeel.jpg"
import Imelda from "../Assets/Players/Imelda.jpg"
import Jeff from "../Assets/Players/Jeff.jpg"
import Much from "../Assets/Players/Much.jpg"
import Ian from "../Assets/Players/Ian.jpg"
import Mutemba from "../Assets/Players/Mutemba.jpg"
import Izo from "../Assets/Players/Izo.jpg"
import Job from "../Assets/Players/Job.jpg"
import Ayub from "../Assets/Players/Ayub.jpg"






export const Players = [
  {
    id: 1,
    name: "Njau",
    position: "Pitcher",
    Jersey: "17",
    gender: "Female",
    image: Njau,
  },
  {
    id: 2,
    name: "Liz",
    position: "Outfielder",
    Jersey: "15",
    gender: "Female",
    image: Liz,
  },
  {
    id: 3,
    name: "Pretty Joy",
    position: "Pitcher",
    Jersey: "7",
    gender: "Female",
    image: Pretty,
  },
  {
    id: 4,
    name: "Sheila",
    position: "Pitcher",
    Jersey: "4",
    gender: "Female",
    image: Sheila,
  },
  {
    id: 5,
    name: "Hallinter",
    position: "Catcher",
    Jersey: "5",
    gender: "Female",
    image: Hallinter,
  },
  {
    id: 6,
    name: "Chebi",
    position: "First Base",
    Jersey: "3",
    gender: "Female",
    image: Chebi,
  },
  {
    id: 7,
    name: "Natasha",
    position: "Second Base",
    Jersey: "7",
    gender: "Female",
    image: Natasha,
  },
  {
    id: 8,
    name: "Mwende",
    position: "Second Base",
    Jersey: "18",
    gender: "Female",
    image: Mwende,
  },
  // {
  //   id: 9,
  //   name: "Imelda",
  //   position: "Shot Stop",
  //   Jersey: "9",
  //   gender: "Female",
  //   image: ("../Assets/Players/Imelda.jpg"),
  // },
  // {
  //   id: 10,
  //   name: "Joy",
  //   position: "Shot Stop",
  //   Jersey: "19",
  //   gender: "Female",
  //   image: ("../Assets/Batting.jpg"),
  // },
  // {
  //   id: 11,
  //   name: "Nakeel",
  //   position: "Third Base",
  //   Jersey: "8",
  //   gender: "Female",
  //   image: ("../Assets/Players/Nakeel.jpg"),
  // },
  // {
  //   id: 12,
  //   name: "Bree",
  //   position: "Outfielder",
  //   Jersey: "6",
  //   gender: "Female",
  //   image: ("../Assets/Players/Bridgit.jpg"),
  // },
  // {
  //   id: 13,
  //   name: "Brenda",
  //   position: "Outfielder",
  //   Jersey: "16",
  //   gender: "Female",
  //   image: ("../Assets/Batting.jpg"),
  // },
  // {
  //   id: 14,
  //   name: "Bridgit",
  //   position: "Outfielder",
  //   Jersey: "17",
  //   gender: "Female",
  //   image: ("../Assets/Batting.jpg"),
  // },
  // {
  //   id: 15,
  //   name: "Mirriam",
  //   position: "Outfielder",
  //   Jersey: "12",
  //   gender: "Female",
  //   image: ("../Assets/Players/Mirriam.jpg"),
  // },
  // {
  //   id: 16,
  //   name: "Yvonne",
  //   position: "Outfielder",
  //   Jersey: "16",
  //   gender: "Female",
  //   image: ("../Assets/Players/Yvonne.jpg"),
  // },
  {
    id: 17,
    name: "Luis Kimutai",
    position: "Pitcher",
    Jersey: "5",
    gender: "male",
    image: Kimutai,
  },
  {
    id: 18,
    name: "Ravi",
    position: "Pitcher",
    Jersey: "22",
    gender: "male",
    image: Ravi,
  },
  {
    id: 19,
    name: "Titus",
    position: "Pitcher",
    Jersey: "13",
    gender: "male",
    image: Titus,
  },
  {
    id: 20,
    name: "Tony",
    position: "Catcher",
    Jersey: "12",
    gender: "male",
    image: Tony,
  },
  {
    id: 21,
    name: "Antonicm",
    position: "Catcher",
    Jersey: "69",
    gender: "male",
    image: Anto,
  },
  {
    id: 22,
    name: "Omar",
    position: "Catcher",
    Jersey: "15",
    gender: "male",
    image: Omar,
  },

  // {
  //   id: 23,
  //   name: "Eleli",
  //   position: "First Baseman",
  //   Jersey: "4",
  //   gender: "male",
  //   image: ("../Assets/Players/Ayub.jpg"),
  // },
  // {
  //   id: 69,
  //   name: "Job",
  //   position: "Second Baseman",
  //   Jersey: "21",
  //   gender: "male",
  //   image: ("../Assets/Players/Job.jpg"),
  // },
  // {
  //   id: 68,
  //   name: "Simon",
  //   position: "Third Baseman",
  //   Jersey: "6",
  //   gender: "male",
  //   image: ("../Assets/Players/Simo.jpg"),
  // },
  // {
  //   id: 67,
  //   name: "Haaron",
  //   position: "Outfield",
  //   Jersey: "3",
  //   gender: "male",
  //   image: ("../Assets/Players/Aaron.jpg"),
  // },
  // {
  //   id: 66,
  //   name: "Amos",
  //   position: "Outfield",
  //   Jersey: "8",
  //   gender: "male",
  //   image: ("../Assets/Players/Amos.jpg"),
  // },
  // {
  //   id: 65,
  //   name: "Jeff",
  //   position: "Shot Stop",
  //   Jersey: "9",
  //   gender: "male",
  //   image: ("../Assets/Players/Jeff.jpg"),
  // },
  // {
  //   id: 64,
  //   name: "Charles",
  //   position: "Outfield",
  //   Jersey: "7",
  //   gender: "male",
  //   image: ("../Assets/Players/Much.jpg"),
  // },
  // {
  //   id: 63,
  //   name: "Ian",
  //   position: "Outfield",
  //   Jersey: "10",
  //   gender: "male",
  //   image: ("../Assets/Players/Ian.jpg"),
  // },
  // {
  //   id: 62,
  //   name: "Mutemba",
  //   position: "Outfielder",
  //   Jersey: "11",
  //   gender: "male",
  //   image: ("../Assets/Players/Mutemba.jpg"),
  // },
  // {
  //   id: 61,
  //   name: "Isaack",
  //   position: "Outfield",
  //   Jersey: "17",
  //   gender: "male",
  //   image: ("../Assets/Players/Izo.jpg"),
  // },
];

export const Fplayers = [
  {
    id: 1,
    name: "Njau",
    position: "Pitcher",
    Jersey: "17",
    gender: "Female",
    image: Njau,
  },
  {
    id: 2,
    name: "Liz",
    position: "Outfielder",
    Jersey: "15",
    gender: "Female",
    image: Liz,
  },
  {
    id: 3,
    name: "Pretty Joy",
    position: "Pitcher",
    Jersey: "7",
    gender: "Female",
    image: Pretty,
  },
  {
    id: 4,
    name: "Sheila",
    position: "Pitcher",
    Jersey: "4",
    gender: "Female",
    image: Sheila,
  },
  {
    id: 5,
    name: "Hallinter",
    position: "Catcher",
    Jersey: "5",
    gender: "Female",
    image: Hallinter,
  },
  {
    id: 6,
    name: "Chebi",
    position: "First Base",
    Jersey: "3",
    gender: "Female",
    image: Chebi,
  },
 

];

export const Mplayers = [

  {
    id: 17,
    name: "Luis Kimutai",
    position: "Pitcher",
    Jersey: "5",
    gender: "male",
    image: Kimutai,
  },
  {
    id: 18,
    name: "Ravi",
    position: "Pitcher",
    Jersey: "22",
    gender: "male",
    image: Ravi,
  },
  {
    id: 19,
    name: "Titus",
    position: "Pitcher",
    Jersey: "13",
    gender: "male",
    image: Titus,
  },
  {
    id: 20,
    name: "Tony",
    position: "Catcher",
    Jersey: "12",
    gender: "male",
    image: Tony,
  },
  {
    id: 21,
    name: "Antonicm",
    position: "Catcher",
    Jersey: "69",
    gender: "male",
    image: Anto,
  },
  {
    id: 22,
    name: "Omar",
    position: "Catcher",
    Jersey: "15",
    gender: "male",
    image: Omar,
  },

];

export const AllMale = [

  {
    id: 17,
    name: "Luis Kimutai",
    position: "Pitcher",
    Jersey: "5",
    gender: "male",
    image: Kimutai,
  },
  {
    id: 18,
    name: "Ravi",
    position: "Pitcher",
    Jersey: "22",
    gender: "male",
    image: Ravi,
  },
  {
    id: 19,
    name: "Titus",
    position: "Pitcher",
    Jersey: "13",
    gender: "male",
    image: Titus,
  },
  {
    id: 20,
    name: "Tony",
    position: "Catcher",
    Jersey: "12",
    gender: "male",
    image: Tony,
  },
  {
    id: 21,
    name: "Antonicm",
    position: "Catcher",
    Jersey: "69",
    gender: "male",
    image: Anto,
  },
  {
    id: 22,
    name: "Omar",
    position: "Catcher",
    Jersey: "15",
    gender: "male",
    image: Omar,
  },

   {
    id: 23,
    name: "Eleli",
    position: "First Baseman",
    Jersey: "4",
    gender: "male",
    image: Ayub,
  },
  {
    id: 69,
    name: "Job",
    position: "Second Baseman",
    Jersey: "21",
    gender: "male",
    image: Job,
  },
  // {
  //   id: 68,
  //   name: "Simon",
  //   position: "Third Baseman",
  //   Jersey: "6",
  //   gender: "male",
  //   image: ("../Assets/Players/Simo.jpg"),
  // },
  // {
  //   id: 67,
  //   name: "Haaron",
  //   position: "Outfield",
  //   Jersey: "3",
  //   gender: "male",
  //   image: ("../Assets/Players/Aaron.jpg"),
  // },
  // {
  //   id: 66,
  //   name: "Amos",
  //   position: "Outfield",
  //   Jersey: "8",
  //   gender: "male",
  //   image: ("../Assets/Players/Amos.jpg"),
  // },
  {
    id: 65,
    name: "Jeff",
    position: "Shot Stop",
    Jersey: "9",
    gender: "male",
    image: Jeff,
  },
  {
    id: 64,
    name: "Charles",
    position: "Outfield",
    Jersey: "7",
    gender: "male",
    image: Much,
  },
  {
    id: 63,
    name: "Ian",
    position: "Outfield",
    Jersey: "10",
    gender: "male",
    image: Ian,
  },
  {
    id: 62,
    name: "Mutemba",
    position: "Outfielder",
    Jersey: "11",
    gender: "male",
    image: Mutemba,
  },
  {
    id: 61,
    name: "Isaack",
    position: "Outfield",
    Jersey: "17",
    gender: "male",
    image: Izo,
  },
];

export const AllFemale = [
  {
    id: 1,
    name: "Njau",
    position: "Pitcher",
    Jersey: "17",
    gender: "Female",
    image: Njau,
  },
  {
    id: 2,
    name: "Liz",
    position: "Outfielder",
    Jersey: "15",
    gender: "Female",
    image: Liz,
  },
  {
    id: 3,
    name: "Pretty Joy",
    position: "Pitcher",
    Jersey: "7",
    gender: "Female",
    image: Pretty,
  },
  {
    id: 4,
    name: "Sheila",
    position: "Pitcher",
    Jersey: "4",
    gender: "Female",
    image: Sheila,
  },
  {
    id: 5,
    name: "Hallinter",
    position: "Catcher",
    Jersey: "5",
    gender: "Female",
    image: Hallinter,
  },
  {
    id: 6,
    name: "Chebi",
    position: "First Base",
    Jersey: "3",
    gender: "Female",
    image: Chebi,
  },
  {
    id: 7,
    name: "Natasha",
    position: "Second Base",
    Jersey: "7",
    gender: "Female",
    image: Natasha,
  },
  {
    id: 8,
    name: "Mwende",
    position: "Second Base",
    Jersey: "18",
    gender: "Female",
    image: Mwende,
  },
  {
    id: 9,
    name: "Imelda",
    position: "Shot Stop",
    Jersey: "9",
    gender: "Female",
    image: Imelda,
  },
  // {
  //   id: 10,
  //   name: "Joy",
  //   position: "Shot Stop",
  //   Jersey: "19",
  //   gender: "Female",
  //   image: ("../Assets/Batting.jpg"),
  // },
  {
    id: 11,
    name: "Nakeel",
    position: "Third Base",
    Jersey: "8",
    gender: "Female",
    image: Nakeel,
  },
  {
    id: 12,
    name: "Bree",
    position: "Outfielder",
    Jersey: "6",
    gender: "Female",
    image: Bridgit,
  },
  // {
  //   id: 13,
  //   name: "Brenda",
  //   position: "Outfielder",
  //   Jersey: "16",
  //   gender: "Female",
  //   image: Brenda,
  // },
  // {
  //   id: 14,
  //   name: "Bridgit",
  //   position: "Outfielder",
  //   Jersey: "17",
  //   gender: "Female",
  //   image: Bridgit,
  // },
  {
    id: 15,
    name: "Mirriam",
    position: "Outfielder",
    Jersey: "12",
    gender: "Female",
    image: Mirriam,
  },
  {
    id: 16,
    name: "Yvonne",
    position: "Outfielder",
    Jersey: "16",
    gender: "Female",
    image: Yvonne,
  },

];
